### ISSUE TITLE
new symbols length >6

### ISSUE THREAD

**Issue by Anarchotrader** [jnidzwetzki/bitfinex-v2-wss-api-java#130] opened 2019-06-26 19:20 UTC
After today's update, Bitfinex add two new lines with strange symbols in the list of Symbols.
https://api.bitfinex.com/v1/symbols_details
{"pair":"btcf0:ustf0","price_precision":5,"initial_margin":"1.0","minimum_margin":"0.5","maximum_order_size":"100.0","minimum_order_size":"0.001","expiration":"NA","margin":false},{"pair":"ethf0:ustf0","price_precision":5,"initial_margin":"1.0","minimum_margin":"0.5","maximum_order_size":"1000.0","minimum_order_size":"0.001","expiration":"NA","margin":false}

That have more then six chars and it let the failure:
Exception in thread "main" com.github.jnidzwetzki.bitfinex.v2.exception.BitfinexClientException: The currency pair is not 6 chars long: btcf0:ustf0
	at com.github.jnidzwetzki.bitfinex.v2.entity.currency.BitfinexCurrencyPair.registerDefaults(BitfinexCurrencyPair.java:62)

It can be solved with replace registerDefaults() in BitfinexCurrencyPair.java:

`	public static void registerDefaults() throws BitfinexClientException {

		try {
			final URL url = new URL(SYMBOL_URL);
			final String symbolJson = Resources.toString(url, Charsets.UTF_8);
			final JSONArray jsonArray = new JSONArray(symbolJson);

			for(int i = 0; i < jsonArray.length(); i++) {
				final JSONObject currency = jsonArray.getJSONObject(i);
				final String pair = currency.getString("pair");

//				if(pair.length() != 6) {
//					throw new BitfinexClientException("The currency pair is not 6 chars long: " + pair);
//				}

				if(pair.length() == 6) {
					final double minOrderSize = currency.getDouble("minimum_order_size");
					final String currency1 = pair.substring(0, 3).toUpperCase();
					final String currency2 = pair.substring(3, 6).toUpperCase();
					register(currency1, currency2, minOrderSize);
				}
			}

		} catch (IOException e) {
			throw new BitfinexClientException(e);
		} 
	}`

**Comment by jnidzwetzki** [comment] 2019-06-26 19:26
Hi,

thanks for the report. The problem is already fixed in the last github version. See https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/commit/8d192c6590b46e2d82c20c2e2cf054619ee0bb8e for more details.

Best Regards
   Jan

**Closed by jnidzwetzki** 2019-06-26 19:26 UTC
