### ISSUE TITLE
spring boot application does not deploy on JBoss if I add bitfinex-v2-wss-api dependency to the pom file. (UT003024: Web socket deployment failed. java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()) 

### ISSUE THREAD

**Issue by HukanaMatata** [jnidzwetzki/bitfinex-v2-wss-api-java#149] opened 2019-12-04 20:30 UTC
Hello,

when i try to deploy the application on JBoss (18.0.1) server this message is displayed in the logs and deployment stops:

```
[2019-12-05 01:28:56,415] Artifact test-spring-jboss:war exploded: Artifact is being deployed, please wait...
01:28:56,701 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "test-spring-jboss-1.0-SNAPSHOT" (runtime-name: "test-spring-jboss-1.0-SNAPSHOT.war")
01:29:02,275 WARN  [org.jboss.as.ee] (MSC service thread 1-7) WFLYEE0007: Not installing optional component org.springframework.http.server.reactive.ServletServerHttpResponse$ResponseAsyncListener due to an exception (enable DEBUG log level to see the cause)
01:29:02,276 WARN  [org.jboss.as.ee] (MSC service thread 1-7) WFLYEE0007: Not installing optional component org.springframework.http.server.reactive.ServletHttpHandlerAdapter$HandlerResultAsyncListener due to an exception (enable DEBUG log level to see the cause)
01:29:02,277 WARN  [org.jboss.as.ee] (MSC service thread 1-7) WFLYEE0007: Not installing optional component org.springframework.http.server.ServletServerHttpAsyncRequestControl due to an exception (enable DEBUG log level to see the cause)
01:29:02,278 WARN  [org.jboss.as.ee] (MSC service thread 1-7) WFLYEE0007: Not installing optional component org.springframework.web.context.request.async.StandardServletAsyncWebRequest due to an exception (enable DEBUG log level to see the cause)
01:29:02,282 WARN  [org.jboss.as.ee] (MSC service thread 1-7) WFLYEE0007: Not installing optional component org.springframework.http.server.reactive.ServletServerHttpRequest$RequestAsyncListener due to an exception (enable DEBUG log level to see the cause)
01:29:02,343 INFO  [io.undertow.websockets.jsr] (ServerService Thread Pool -- 142) UT026004: Adding annotated client endpoint class com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint
01:29:02,344 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 142) MSC000001: Failed to start service jboss.deployment.unit."test-spring-jboss-1.0-SNAPSHOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."test-spring-jboss-1.0-SNAPSHOT.war".undertow-deployment: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:93)
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:279)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:155)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 9 more
Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:700)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpoint(ServerWebSocketContainer.java:622)
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:87)
	... 13 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()
	at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:59)
	at org.jboss.as.ee.component.ComponentRegistry.createInstanceFactory(ComponentRegistry.java:76)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$ComponentClassIntrospector.createInstanceFactory(UndertowDeploymentInfoService.java:1290)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:694)
	... 15 more
Caused by: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:57)
	... 18 more

01:29:02,347 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 4) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "test-spring-jboss-1.0-SNAPSHOT")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"test-spring-jboss-1.0-SNAPSHOT.war\".undertow-deployment" => "java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()"}}
01:29:02,348 ERROR [org.jboss.as.server] (management-handler-thread - 4) WFLYSRV0021: Deploy of deployment "test-spring-jboss-1.0-SNAPSHOT.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"test-spring-jboss-1.0-SNAPSHOT.war\".undertow-deployment" => "java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()"}}
01:29:02,463 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0028: Stopped deployment test-spring-jboss-1.0-SNAPSHOT (runtime-name: test-spring-jboss-1.0-SNAPSHOT.war) in 115ms
[2019-12-05 01:29:02,563] Artifact test-spring-jboss:war exploded: Error during artifact deployment. See server log for details.
[2019-12-05 01:29:02,563] Artifact test-spring-jboss:war exploded: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"test-spring-jboss-1.0-SNAPSHOT.war\".undertow-deployment" => "java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.<init>()"}}
```

POM.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test-spring-jboss</groupId>
    <artifactId>test-spring-jboss</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.1.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.jnidzwetzki</groupId>
            <artifactId>bitfinex-v2-wss-api</artifactId>
            <version>0.7.5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

SpringBootDemoApplication.java
```
@SpringBootApplication
public class SpringBootDemoApplication extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder builder){
        return builder.sources(SpringBootDemoApplication.class);
    }
    public static void main(String[] args){
        SpringApplication.run(SpringBootDemoApplication.class, args);
    }
}
```

Please help,

Thanks

**Comment by HukanaMatata** [comment] 2019-12-04 22:54
I disabled web sockets support in JBoss settings. But this is temporary solution. I think there is a better way around the problem.

wildfly_dir\standalone\configuration\standalone.xml:
```
            <servlet-container name="default">
                <jsp-config/>
                <!-- websockets/ -->
            </servlet-container>
```

How to exclude `com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint` class from auto-scanning by server? I think Spring has nothing to do with it. Exactly server tries to create an instance but does not find default constructor.

**Comment by jnidzwetzki** [comment] 2019-12-06 06:50
Hi,

Thanks for your report. This problem might be caused by an incompatibility of the used libraries of JBoss and this project. I found a lot of similar error messages in projects that are using an own Websocket Library in JBoss. 


Please try to add the following lines to your pom.xml

    ```
    <dependency>
            <groupId>javax.websocket</groupId>
            <artifactId>javax.websocket-api</artifactId>
            <version>1.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.tyrus.bundles</groupId>
            <artifactId>tyrus-standalone-client</artifactId>
            <version>1.15</version>
            <scope>provided</scope>
        </dependency>
```

Best Regards
   Jan

**Comment by HukanaMatata** [comment] 2019-12-06 19:28
Hi,

Thank you for the answer.
I added these dependencies into pom file but this did not help. I get the same error when deploying.

**Comment by jnidzwetzki** [comment] 2019-12-10 15:25
Good Morning,

Thank you for the reply. Unfortunately, I'm no expert on JBoss. I suppose that your question is better answered in a group for JBoss users. As far as I understand the error message, this seems to be a problem with the dependency management in JBoss. In addition, you could post your question in our Gitter chat (https://gitter.im/bitfinex-v2-wss-api-java/Lobby). Maybe there are some JBoss experts available.

Best Regards
   Jan

**Comment by mironbalcerzak** [comment] 2020-04-09 11:56
Hi @jnidzwetzki, hope all's good. Should we close this "issue"?

**Comment by jnidzwetzki** [comment] 2020-04-09 12:02
Because there is no activity in this issue for several moths, I will close the ticket.

**Closed by jnidzwetzki** 2020-04-09 12:02 UTC

**Comment by zevolution** [comment] 2020-07-10 23:43
@HukanaMatata Did you get a solution to this problem? I'm using Wildfly 18.0.1 + Spring Boot 2.2.2.RELEASE with a class annotated with `@ClientEndpoint` and I have the same problem, before receiving an error this is the message which I receive `"Adding annotated client endpoint class br.com.zevolution.integracoes.vocallcenter.lib.sockets.RamalSocketClient"`. 

Stacktrace:
```
2020-07-10 23:22:28,139 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 686) MSC000001: Failed to start service jboss.deployment.unit."vocall-center-app-1.0.0.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."vocall-center-app-1.0.0.war".undertow-deployment: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:485)
```
